### ISSUE TITLE
APCtray exiting after few seconds

### ISSUE THREAD

**Issue by jimmycr** [therealbstern/apcupsd#3]
Windows 11 - "apctray" showing in tray for a few seconds only, then disappears (even the process is not showing in process manager). Have to rerun manually, but after few seconds the problem occurs again...

- apcupsd 3.14.14
- windows 11
- apcupsd running as a service
- apctray set to run automatically

edit: several restarts and now it holds... sorry for opening this topic :(

**Comment by therealbstern** [comment]
I recommend you check with the apcupsd-users mailing list at https://sourceforge.net/p/apcupsd/mailman/

You should also check the application event log and make sure there isn't a configuration error.

I'm not the official source for APCUPSd, I just posted these patches here so they wouldn't get lost.

**Comment by therealbstern** [comment]
Apparently it's working now, so my previous advice was not relevant.  Glad it's working now!

**Comment by jimmycr** [comment]
Not working again :( . No icon in tray, when manually executed, icon shows up for a few seconds and disappear. Don't know why :( What was "previous advice"? Already tried to run as administrator...

**Comment by therealbstern** [comment]
Try subscribing to the official users' list, which still seems active:
https://sourceforge.net/p/apcupsd/mailman/apcupsd-users/

Is there anything in the Application Log?  (I think this means check Event Viewer in Windows, but maybe APCUPSd writes its own log.)  According to some messages on the users mailing list, this can be caused by an invalid configuration file.  https://sourceforge.net/p/apcupsd/mailman/message/37405765/ is a little hard to read but discusses APCTray breaking due to a configuration problem.

**Comment by jimmycr** [comment]
Service is working fine, only APCTRAY is failing. will try to check logs (if any exists) and go through mailinglists ;-)
